branch-defaults:
  master:
    environment: production
  prod:
    environment: production
environment-defaults:
  production:
    branch: null
    repository: null
global:
  application_name: blog.christophermedlin.me
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
